apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  podGC:
    strategy: OnWorkflowSuccess
  onExit: notify-slack
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "{{inputs.parameters.message}}" ]

    ##
    ## Send a Slack notification describing the final status of the workflow.
    ##
    - name: notify-slack
      templateRef:
        name: {{ .Values.argoTemplates.notification.name }}
        template: send-slack-notification
      arguments:
        parameters:
        - name: channel
          value: {{ .Values.notification.channelId }}
        - name: text
          value:  "Workflow $(WORKFLOW_ID) in env *$(WORKFLOW_ENV)* entered state: *$(WORKFLOW_STATE)*"
