apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-dataset
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: dataset-name
          - name: bq-project
          - name: dataset-description
          - name: dataset-expiration
      script:
        image: google/cloud-sdk:slim
        env:
          - name: PROJECT
            value: '{{ "{{inputs.parameters.bq-project}}" }}'
          - name: DATASET
            value: '{{ "{{inputs.parameters.dataset-name}}" }}'
          - name: DESCRIPTION
            value: '{{ "{{inputs.parameters.dataset-description}}" }}'
          - name: EXPIRATION
            value: '{{ "{{inputs.parameters.dataset-expiration}}" }}'
        command: [bash]
        source: |
          {{- range .Files.Lines "scripts/create-bq-dataset.sh" }}
          {{ . }}
          {{- end }}
