{{- $YYYY := "{{workflow.creationTimestamp.Y}}" }}
{{- $mm := "{{workflow.creationTimestamp.m}}" }}
{{- $dd := "{{workflow.creationTimestamp.d}}" }}
{{- $HH := "{{workflow.creationTimestamp.H}}" }}
{{- $MM := "{{workflow.creationTimestamp.M}}" }}
{{- $SS := "{{workflow.creationTimestamp.S}}" }}
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: clinvar-ingest
spec:
  suspend: {{ not .Values.cron.enable }}
  schedule: {{ .Values.cron.schedule | quote }}
  timezone: {{ .Values.cron.timezone | quote }}
  concurrencyPolicy: Forbid
  workflowSpec:
    entrypoint: main
    serviceAccountName: {{ .Values.serviceAccount.k8sName }}
    podGC:
      strategy: OnWorkflowSuccess
    templates:
      - name: main
        templateRef:
          name: ingest-clinvar-archive
          template: main
        inputs:
          parameters:
            - name: archive-path
              value: weekly_release/ClinVarVariationRelease_00-latest_weekly.xml.gz
            - name: gcs-prefix
              value: '{{ printf "%s-%s-%sT%s:%s:%s" $YYYY $mm $dd $HH $MM $SS }}'
