apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: clinvar-ingest
spec:
  suspend: {{ not .Values.cron.enable }}
  schedule: '{{ .Values.cron.schedule }}'
  concurrencyPolicy: Deny
  workflowSpec:
    entrypoint: main
      podGC:
        strategy: OnWorkflowSuccess
    templates:
      - name: main
        templateRef:
          name: ingest-clinvar-archive
          template: main
        inputs:
          parameters:
            - name: archive-path
              value: weekly_release/ClinVarVariationRelease_00-latest_weekly.xml.gz
            - name: gcs-prefix
              value: '{{ printf "{{workflow.creationTimestamp.%s}}" .Values.cron.timestampPattern }}'
