apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: date-present
spec:
  entrypoint: main
  serviceAccountName: {{ .Values.serviceAccount.k8sName }}
  templates:
    ##
    ## Entrypoint for if there is a previous date against which to diff.
    ##
    ##
    - name: main
      inputs:
        parameters:
          - name: table-name
          {{- $tableName := "{{inputs.parameters.table-name}}" }}
          - name: gcs-prefix
          {{- $gcsPrefix := "{{inputs.parameters.gcs-prefix}}" }}
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
          - name: pipeline-version
          {{- $pipelineVersion := "{{inputs.parameters.pipeline-version}}" }}
          - name: dataset-name
          {{- $destDatasetName := "{{inputs.parameters.dataset-name}}" }}
      dag:
        tasks:
          # get preceding date
          - name: get-preceding-date
            arguments:
              parameters:
                - name: release-date
                  value: {{ $releaseDate | quote }}
                - name: pipeline-version
                  value: {{ $pipelineVersion | quote }}
                - name: table-name
                  value: {{ $tableName | quote }}

          {{- $precedingDate := "{{tasks.get-preceding-date.outputs.result}}" }}
          ## get created rows
          - name: get-created-rows
            dependencies: [get-preceding-date]
            template: get-created-rows
            arguments:
              parameters:
                - name: table-name
                  value: {{ $tableName | quote }}
                - name: dest-dataset-name
                  value: {{ $destDatasetName | quote }}
                - name: release-date
                  value: {{ $releaseDate | quote }}
                - name: prev-date
                  value: {{ $precedingDate | quote }}

          # export created rows to bucket
          - name: export-created-rows
            dependencies: [get-created-rows]
            template: export-rows
            arguments:
              parameters:
                - name: table-name
                  value: {{ $tableName | quote }}
                - name: dest-dataset-name
                  value: {{ $destDatasetName | quote }}
                - name: diff-type
                  value: CREATE

          ## get deleted rows
          - name: get-deleted-rows
            dependencies: [get-preceding-date]
            template: get-deleted-rows
            arguments:
              parameters:
                - name: table-name
                  value: {{ $tableName | quote }}
                - name: dest-dataset-name
                  value: {{ $destDatasetName | quote }}
                - name: release-date
                  value: {{ $releaseDate | quote }}
                - name: prev-date
                  value: {{ $precedingDate | quote }}

          # export deleted rows to bucket
          - name: export-deleted-rows
            dependencies: [get-deleted-rows]
            template: export-rows
            arguments:
              parameters:
                - name: table-name
                  value: {{ $tableName | quote }}
                - name: dest-dataset-name
                  value: {{ $destDatasetName | quote }}
                - name: diff-type
                  value: DELETE

          ## get updated rows
          - name: get-updated-rows
            dependencies: [get-preceding-date]
            template: get-updated-rows
            arguments:
              parameters:
                - name: table-name
                  value: {{ $tableName | quote }}
                - name: dest-dataset-name
                  value: {{ $destDatasetName | quote }}
                - name: release-date
                  value: {{ $releaseDate | quote }}
                - name: prev-date
                  value: {{ $precedingDate | quote }}

          # export updated rows to bucket
          - name: export-updated-rows
            dependencies: [get-updated-rows]
            template: export-rows
            arguments:
              parameters:
                - name: table-name
                  value: {{ $tableName | quote }}
                - name: dest-dataset-name
                  value: {{ $destDatasetName | quote }}
                - name: diff-type
                  value: UPDATE

    - name: get-preceding-date
      inputs:
        parameters:
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
          - name: pipeline-version
          {{- $pipelineVersion := "{{inputs.parameters.pipeline-version}}" }}
          - name: table-name
          {{- $tableName := "{{inputs.parameters.table-name}}" }}
      script:
        image: google/cloud-sdk:slim
        command: [bash]
        env:
          - name: JADE_PROJECT
            value: {{ .Values.jade.dataProject }}
          - name: JADE_DATASET
            value: {{ printf "datarepo_%s" .Values.jade.datasetName }}
          - name: RELEASE_DATE
            value: {{ $releaseDate | quote }}
          - name: VERSION
            value: {{ $pipelineVersion | quote }}
          - name: TABLE
            value: {{ $tableName | quote }}
        source: |
        {{- include "argo.render-lines" (.Files.Lines "scripts/get-preceding-release-date.sh") | indent 10 }}

    - name: get-created-rows
      inputs:
        parameters:
          - name: table-name
          {{- $tableName := "{{inputs.parameters.table-name}}" }}
          - name: dest-dataset-name
          {{- $destDatasetName := "{{inputs.parameters.dest-dataset-name}}" }}
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
          - name: prev-date
          {{- $precedingDate := "{{inputs.parameters.prev-date}}" }}
      volumes:
        - name: sa-secret-volume
          secret:
            secretName: {{ .Values.jade.accessKey.secretName }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/monster-bq-diff:1.0.0
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ printf "/secret/%s" .Values.jade.accessKey.secretKey }}
          - name: TABLE_NAME
            value: {{ $tableName | quote }}
          - name: DEST_DATA_PROJECT
            value: {{ .Values.clingen.project }}
          - name: DEST_DATASET_NAME
            value: {{ $destDatasetName | quote }}
          - name: REPO_DATA_PROJECT
            value: {{ .Values.jade.dataProject }}
          - name: REPO_DATASET_NAME
            value: {{ .Values.jade.datasetName }}
          - name: RELEASE_DATE
            value: {{ $releaseDate | quote }}
          - name: PREV_DATE
            value: {{ $precedingDate | quote }}
          - name: VERSION_COL
            value: release_date
          - name: DIFF_TYPE
            value: CREATE
        command: [python]
        source: |
          from diff import get_created_rows
          get_created_rows()

    - name: get-deleted-rows
      inputs:
        parameters:
          - name: table-name
          {{- $tableName := "{{inputs.parameters.table-name}}" }}
          - name: dest-dataset-name
          {{- $destDatasetName := "{{inputs.parameters.dest-dataset-name}}" }}
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
          - name: prev-date
          {{- $precedingDate := "{{inputs.parameters.prev-date}}" }}
      volumes:
        - name: sa-secret-volume
          secret:
            secretName: {{ .Values.jade.accessKey.secretName }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/monster-bq-diff:1.0.0
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ printf "/secret/%s" .Values.jade.accessKey.secretKey }}
          - name: TABLE_NAME
            value: {{ $tableName | quote }}
          - name: DEST_DATA_PROJECT
            value: {{ .Values.clingen.project }}
          - name: DEST_DATASET_NAME
            value: {{ $destDatasetName | quote }}
          - name: REPO_DATA_PROJECT
            value: {{ .Values.jade.dataProject }}
          - name: REPO_DATASET_NAME
            value: {{ .Values.jade.datasetName }}
          - name: RELEASE_DATE
            value: {{ $releaseDate | quote }}
          - name: PREV_DATE
            value: {{ $precedingDate | quote }}
          - name: VERSION_COL
            value: release_date
          - name: DIFF_TYPE
            value: DELETE
        command: [python]
        source: |
          from diff import get_deleted_rows
          get_deleted_rows()

    - name: get-updated-rows
      inputs:
        parameters:
          - name: table-name
          {{- $tableName := "{{inputs.parameters.table-name}}" }}
          - name: dest-dataset-name
          {{- $destDatasetName := "{{inputs.parameters.dest-dataset-name}}" }}
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
          - name: prev-date
          {{- $precedingDate := "{{inputs.parameters.prev-date}}" }}
      volumes:
        - name: sa-secret-volume
          secret:
            secretName: {{ .Values.jade.accessKey.secretName }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/monster-bq-diff:1.0.0
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ printf "/secret/%s" .Values.jade.accessKey.secretKey }}
          - name: TABLE_NAME
            value: {{ $tableName | quote }}
          - name: DEST_DATA_PROJECT
            value: {{ .Values.clingen.project }}
          - name: DEST_DATASET_NAME
            value: {{ $destDatasetName | quote }}
          - name: REPO_DATA_PROJECT
            value: {{ .Values.jade.dataProject }}
          - name: REPO_DATASET_NAME
            value: {{ .Values.jade.datasetName }}
          - name: RELEASE_DATE
            value: {{ $releaseDate | quote }}
          - name: PREV_DATE
            value: {{ $precedingDate | quote }}
          - name: VERSION_COL
            value: release_date
          - name: DIFF_TYPE
            value: UPDATE
        command: [python]
        source: |
          from diff import get_updated_rows
          get_updated_rows()

    - name: export-rows
      inputs:
        parameters:
          - name: table-name
          {{- $tableName := "{{inputs.parameters.table-name}}" }}
          - name: dest-dataset-name
          {{- $destDatasetName := "{{inputs.parameters.dest-dataset-name}}" }}
          - name: diff-type
          {{- $diffType := "{{inputs.parameters.diff-type}}" }}
      volumes:
        - name: sa-secret-volume
          secret:
            secretName: {{ .Values.jade.accessKey.secretName }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/monster-bq-diff:1.0.0
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ printf "/secret/%s" .Values.jade.accessKey.secretKey }}
          - name: TABLE_NAME
            value: {{ $tableName | quote }}
          - name: DEST_DATA_PROJECT
            value: {{ .Values.clingen.project }}
          - name: DEST_DATASET_NAME
            value: {{ $destDatasetName | quote }}
          - name: DEST_BUCKET_NAME
            value: {{ .Values.clingen.gcsBucket }}
          - name: DIFF_TYPE
            value: {{ $diffType | quote }}
        command: [python]
        source: |
          from diff import extract_rows
          extract_rows()