apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: date-absent
spec:
  entrypoint: main
  serviceAccountName: {{ .Values.serviceAccount.k8sName }}
  templates:
    ##
    ## Entrypoint for if there is not a previous date against which to diff.
    ##
    ##
    - name: main
      inputs:
        parameters:
          - name: table-name
          {{- $tableName := "{{inputs.parameters.table-name}}" }}
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
          - name: gcs-prefix
          {{- $gcsPrefix := "{{inputs.parameters.gcs-prefix}}" }}
          - name: dataset-name
          {{- $destDatasetName := "{{inputs.parameters.dataset-name}}" }}
      dag:
        tasks:
          - name: get-all-rows
            volumes:
              - name: sa-secret-volume
                secret:
                  secretName: {{ .Values.jade.accessKey.secretName }}
            script:
              image: us.gcr.io/broad-dsp-gcr-public/monster-bq-diff:1.0.0
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: {{ printf "/secret/%s" .Values.jade.accessKey.secretKey }}
                - name: TABLE_NAME
                  value: {{ $tableName | quote }}
                - name: DEST_DATA_PROJECT
                  value: {{ .Values.clingen.project }}
                - name: DEST_DATASET_NAME
                  value: {{ $destDatasetName | quote }}
                {{- with .Values.jade }}
                - name: REPO_DATA_PROJECT
                  value: {{ .dataProject }}
                - name: REPO_DATASET_NAME
                  value: {{ .datasetName }}
                {{- end }}
                - name: RELEASE_DATE
                  value: {{ $releaseDate | quote }}
                - name: VERSION_COL
                  value: release_date
              command: [python]
              source: |
                from diff import get_all_rows
                get_all_rows()

          - name: export-all-rows
            dependencies: [get-all-rows]
            volumes:
              - name: sa-secret-volume
                secret:
                  secretName: {{ .Values.jade.accessKey.secretName }}
            script:
              image: us.gcr.io/broad-dsp-gcr-public/monster-bq-diff:1.0.0
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: {{ printf "/secret/%s" .Values.jade.accessKey.secretKey }}
                - name: TABLE_NAME
                  value: {{ $tableName | quote }}
                - name: DEST_DATA_PROJECT
                  value: {{ .Values.clingen.project }}
                - name: DEST_DATASET_NAME
                  value: {{ $destDatasetName | quote }}
                - name: DEST_BUCKET_NAME
                  value: {{ .Values.clingen.gcsBucket }}
                - name: DIFF_TYPE
                  value: CREATE
              command: [python]
              source: |
                from diff import extract_rows
                extract_rows()