apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: diff-table
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: table-name
          - name: gcs-bucket
          - name: input-prefix
          - name: output-prefix
          - name: staging-bq-project
          - name: staging-bq-dataset
          - name: jade-bq-project
          - name: jade-bq-dataset
      dag:
        tasks:
          # 1) Build a join table containing both IDs to delete and new rows to append.
          - name: join-staging-to-existing
            template: join-staging-to-existing
            arguments:
              parameters:
                - name: table-name
                  value: '{{ "{{inputs.parameters.table-name}}" }}'
                - name: gcs-bucket
                  value: '{{ "{{inputs.parameters.gcs-bucket}}" }}'
                - name: input-prefix
                  value: '{{ "{{inputs.parameters.input-prefix}}" }}'
                - name: staging-bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: staging-bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
                - name: jade-bq-project
                  value: '{{ "{{inputs.parameters.jade-bq-project}}" }}'
                - name: jade-bq-dataset
                  value: '{{ "{{inputs.parameters.jade-bq-dataset}}" }}'
                - name: output-table-suffix
                  value: '{{ template "argo.timestamp" }}'
          # 2a) Query just the IDs to delete from the join table.
          - name: query-ids-to-delete
            dependencies: [join-staging-to-existing]
            template: query-ids-to-delete
            arguments:
              parameters:
                - name: table-name
                  value: '{{ "{{inputs.parameters.table-name}}" }}'
                - name: join-table-name
                  value: '{{ "{{tasks.join-staging-to-existing.outputs.result}}" }}'
                - name: bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
                - name: output-table-suffix
                  value: '{{ template "argo.timestamp" }}'
          # 3a) Extract the query result to GCS.
          - name: extract-ids-to-delete
            dependencies: [query-ids-to-delete]
            template: extract-bq-table
            arguments:
              parameters:
                - name: input-table-name
                  value: '{{ "{{tasks.query-ids-to-delete.outputs.result}}" }}'
                - name: bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
                - name: output-format
                  value: CSV
                - name: gcs-bucket
                  value: '{{ "{{inputs.parameters.gcs-bucket}}" }}'
                - name: gcs-prefix
                  value: '{{ "{{inputs.parameters.output-prefix}}/ids-to-delete" }}'
          # 2b) Query just the rows to append from the join table.
          - name: query-rows-to-append
            dependencies: [join-staging-to-existing]
            template: query-rows-to-append
            arguments:
              parameters:
                - name: table-name
                  value: '{{ "{{inputs.parameters.table-name}}" }}'
                - name: join-table-name
                  value: '{{ "{{tasks.join-staging-to-existing.outputs.result}}" }}'
                - name: bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
                - name: output-table-suffix
                  value: '{{ template "argo.timestamp" }}'
          # 3b) Extract the query result to GCS.
          - name: extract-rows-to-append
            dependencies: [query-rows-to-append]
            template: extract-bq-table
            arguments:
              parameters:
                - name: input-table-name
                  value: '{{ "{{tasks.query-rows-to-append.outputs.result}}" }}'
                - name: bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
                - name: output-format
                  value: NEWLINE_DELIMITED_JSON
                - name: gcs-bucket
                  value: '{{ "{{inputs.parameters.gcs-bucket}}" }}'
                - name: gcs-prefix
                  value: '{{ "{{inputs.parameters.output-prefix}}/rows-to-append" }}'
      outputs:
        parameters:
          - name: ids-to-delete-prefix
            valueFrom:
              parameter: '{{ "{{tasks.extract-ids-to-delete.outputs.result}}" }}'
          - name: rows-to-append-prefix
            valueFrom:
              parameter: '{{ "{{tasks.extract-rows-to-append.outputs.result}}" }}'

    - name: join-staging-to-existing
      inputs:
        parameters:
          - name: table-name
          - name: gcs-bucket
          - name: input-prefix
          - name: staging-bq-project
          - name: staging-bq-dataset
          - name: jade-bq-project
          - name: jade-bq-dataset
          - name: output-table-suffix
      {{- include "argo.retry" . | indent 6 }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/clinvar-schema:{{ default "latest" .Chart.AppVersion }}
        env:
          - name: STAGING_PROJECT
            value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
          - name: STAGING_DATASET
            value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
          - name: JADE_PROJECT
            value: '{{ "{{inputs.parameters.jade-bq-project}}" }}'
          - name: JADE_DATASET
            value: '{{ "{{inputs.parameters.jade-bq-dataset}}" }}'
          - name: TABLE
            value: '{{ "{{inputs.parameters.table-name}}" }}'
          - name: GCS_PREFIX
            value: '{{ "gs://{{inputs.parameters.gcs-bucket}}/{{inputs.parameters.input-prefix}}" }}'
          - name: OUTPUT_SUFFIX
            value: '{{ "{{inputs.parameters.output-table-suffix}}" }}'
        command: [bash]
        source: |
          {{- /* More verbose than I expected, but direct injection is too hard to format. */}}
          {{- range .Files.Lines "scripts/diff-bq-table.sh" }}
          {{ . }}
          {{- end }}

    - name: query-ids-to-delete
      inputs:
        parameters:
          - name: table-name
          - name: join-table-name
          - name: bq-project
          - name: bq-dataset
          - name: output-table-suffix
      {{- include "argo.retry" . | indent 6 }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/clinvar-schema:{{ default "latest" .Chart.AppVersion }}
        env:
          - name: PROJECT
            value: '{{ "{{inputs.parameters.bq-project}}" }}'
          - name: DATASET
            value: '{{ "{{inputs.parameters.bq-dataset}}" }}'
          - name: INPUT_TABLE
            value: '{{ "{{inputs.parameters.join-table-name}}" }}'
          - name: OUTPUT_PREFIX
            value: '{{ "{{inputs.parameters.table-name}}" }}'
          - name: OUTPUT_SUFFIX
            value: '{{ "{{inputs.parameters.output-table-suffix}}" }}'
        command: [bash]
        source: |
          {{- range .Files.Lines "scripts/query-non-null-row-ids.sh" }}
          {{ . }}
          {{- end }}

    - name: query-rows-to-append
      inputs:
        parameters:
          - name: table-name
          - name: join-table-name
          - name: bq-project
          - name: bq-dataset
          - name: output-table-suffix
      {{- include "argo.retry" . | indent 6 }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/clinvar-schema:{{ default "latest" .Chart.AppVersion }}
        env:
          - name: PROJECT
            value: '{{ "{{inputs.parameters.bq-project}}" }}'
          - name: DATASET
            value: '{{ "{{inputs.parameters.bq-dataset}}" }}'
          - name: INPUT_TABLE
            value: '{{ "{{inputs.parameters.join-table-name}}" }}'
          - name: TABLE
            value: '{{ "{{inputs.parameters.table-name}}" }}'
          - name: OUTPUT_SUFFIX
            value: '{{ "{{inputs.parameters.output-table-suffix}}" }}'
        command: [bash]
        source: |
          {{- range .Files.Lines "scripts/query-non-null-rows.sh" }}
          {{ . }}
          {{- end }}

    - name: extract-bq-table
      inputs:
        parameters:
          - name: input-table-name
          - name: bq-project
          - name: bq-dataset
          - name: output-format
          - name: gcs-bucket
          - name: gcs-prefix
      {{- include "argo.retry" . | indent 6 }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/clinvar-schema:{{ default "latest" .Chart.AppVersion }}
        env:
          - name: PROJECT
            value: '{{ "{{inputs.parameters.bq-project}}" }}'
          - name: DATASET
            value: '{{ "{{inputs.parameters.bq-dataset}}" }}'
          - name: TABLE
            value: '{{ "{{inputs.parameters.input-table-name}}" }}'
          - name: OUTPUT_FORMAT
            value: '{{ "{{inputs.parameters.output-format}}" }}'
          - name: GCS_BUCKET
            value: '{{ "{{inputs.parameters.gcs-bucket}}" }}'
          - name: GCS_PREFIX
            value: '{{ "{{inputs.parameters.gcs-prefix}}" }}'
        command: [bash]
        source: |
          {{- range .Files.Lines "scripts/extract-bq-table.sh" }}
          {{ . }}
          {{- end }}
