apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: diff-table
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: table-name
          - name: gcs-bucket
          - name: input-prefix
          - name: staging-bq-project
          - name: staging-bq-dataset
          - name: jade-bq-project
          - name: jade-bq-dataset
      dag:
        tasks:
          - name: join-staging-to-existing
            template: join-staging-to-existing
            arguments:
              parameters:
                - name: table-name
                  value: '{{ "{{inputs.parameters.table-name}}" }}'
                - name: gcs-bucket
                  value: '{{ "{{inputs.parameters.gcs-bucket}}" }}'
                - name: input-prefix
                  value: '{{ "{{inputs.parameters.input-prefix}}" }}'
                - name: staging-bq-project
                  value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
                - name: staging-bq-dataset
                  value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
                - name: jade-bq-project
                  value: '{{ "{{inputs.parameters.jade-bq-project}}" }}'
                - name: jade-bq-dataset
                  value: '{{ "{{inputs.parameters.jade-bq-dataset}}" }}'

    - name: join-staging-to-existing
      inputs:
        parameters:
          - name: table-name
          - name: gcs-bucket
          - name: input-prefix
          - name: staging-bq-project
          - name: staging-bq-dataset
          - name: jade-bq-project
          - name: jade-bq-dataset
      script:
        image: us.gcr.io/broad-dsp-gcr-public/clinvar-schema:{{ default "latest" .Chart.AppVersion }}
        env:
          - name: STAGING_PROJECT
            value: '{{ "{{inputs.parameters.staging-bq-project}}" }}'
          - name: STAGING_DATASET
            value: '{{ "{{inputs.parameters.staging-bq-dataset}}" }}'
          - name: JADE_PROJECT
            value: '{{ "{{inputs.paramaters.jade-bq-project}}" }}'
          - name: JADE_DATASET
            value: '{{ "{{inputs.parameters.jade-bq-dataset}}" }}'
          - name: TABLE
            value: '{{ "{{inputs.parameters.table-name}}" }}'
          - name: GCS_PREFIX
            value: '{{ "gs://{{inputs.parameters.gcs-bucket}}/{{inputs.parameters.input-prefix}}" }}'
          - name: OUTPUT_SUFFIX
            value: '{{ template "argo.timestamp" }}'
        command: [bash]
        source: |
          set -euo pipefail

          # Copy-pasted from StackOverflow.
          function join_by { local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}"; }

          declare -r TABLE_DIR=/bq-metadata/${TABLE}
          declare -r PK_COLS=$(cat ${TABLE_DIR}/primary-keys)
          declare -r COMPARE_COLS=$(cat ${TABLE_DIR}/compare-cols)
          declare -a COMPARISONS=()

          for c in ${COMPARE_COLS//,/ }; do
            COMPARISONS+=("TO_JSON_STRING(S.${c}) != TO_JSON_STRING(J.${c})")
          done

          declare -r FULL_DIFF=$(join_by ' OR ' "${COMPARISONS[@]}")

          bq --location=US --project_id=${STAGING_PROJECT} --synchronous_mode=true --headless=true --format=none query \
            --use_legacy_sql=false \
            --external_table_definition=${TABLE}::${TABLE_DIR}/schema.json@NEWLINE_DELIMITED_JSON=${GCS_PREFIX}/${TABLE}/* \
            --destination_table=${STAGING_PROJECT}:${STAGING_DATASET}.${TABLE}_${OUTPUT_SUFFIX} \
            "SELECT J.datarepo_row_id, S.*
             FROM ${TABLE} S FULL JOIN \`${JADE_PROJECT}.${JADE_DATASET}.${TABLE}\` J
             USING (${PK_COLS}) WHERE ${FULL_DIFF}"
