apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: download-ftp-file
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: ftp-site
          - name: ftp-path
          - name: local-path
          - name: pvc-name
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: '{{ "{{inputs.parameters.pvc-name}}" }}'
      {{- include "argo.retry" . | indent 6 }}
      container:
        image: cirrusci/wget
        command: [wget]
        args:
          # Restart from any state
          - --continue
          # Reset the download connection if it goes idle for > 30 seconds.
          - --read-timeout=30
          - --output-document=/state/{{ "{{inputs.parameters.local-path}}" }}
          - ftp://{{ "{{inputs.parameters.ftp-site}}" }}/{{ "{{inputs.parameters.ftp-path}}" }}
        volumeMounts:
          - name: state
            mountPath: /state
        resources:
          requests:
            memory: 512Mi
            cpu: 1000m
          limits:
            memory: 512Mi
            cpu: 1000m
