apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: download-clinvar-archive
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: archive-path
          - name: download-name
      dag:
        tasks:
          - name: generate-download-volume
            templateRef:
              name: generate-pvc
              template: main
            arguments:
              parameters:
                - name: name-prefix
                  value: ftp-download
                - name: size
                  value: 1Gi
                - name: storage-class
                  value: standard
          - name: download-ftp-file
            dependencies: [generate-download-volume]
            templateRef:
              name: download-ftp-file
              template: main
            arguments:
              parameters:
                - name: ftp-site
                  value: ftp.ncbi.nlm.nih.gov
                - name: ftp-path
                  value: pub/clinvar/xml/clinvar_variation/{{ "{{inputs.parameters.archive-path}}" }}
                - name: local-path
                  value: '{{ "{{inputs.parameters.download-name}}" }}'
                - name: pvc-name
                  value: '{{ "{{tasks.generate-download-volume.outputs.parameters.pvc-name}}" }}'
      outputs:
        parameters:
          - name: pvc-name
            valueFrom:
              parameter: '{{ "{{tasks.generate-download-volume.outputs.parameters.pvc-name}}" }}'
