apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dual-writer-clinvar-ingest
spec:
  suspend: {{ not .Values.cron.enable }}
  schedule: {{ .Values.cron.schedule | quote }}
  timezone: {{ .Values.cron.timezone | quote }}
  concurrencyPolicy: Forbid
  workflowSpec:
    entrypoint: main
    arguments:
      parameters:
        - name: jade-dataset-id
          value: FAKE_DATASET_ID
        - name: jade-dataset-name
          value: FAKE_DATASET_NAME
        - name: jade-data-project
          value: FAKE_DATA_PROJECT_NAME
        - name: jade-url
          value: FAKE_URL
        - name: jade-profile-id
          value: FAKE_PROFILE_ID
    serviceAccountName: {{ .Values.serviceAccount.k8sName }}
    podGC:
      strategy: OnWorkflowSuccess
    templates:
      ##
      ## Main entry-point to the regularly-run ClinVar ingest workflow.
      ##
      ## Delegates to a WorkflowTemplate for all of the business logic,
      ## to support easily running manual ingests.
      ##
      - name: main
        steps:
          - - name: run-main-template
              templateRef:
                name: ingest-clinvar-release-e2e
                template: main
              arguments:
                parameters:
                  - name: archive-path
                    value: weekly_release/ClinVarVariationRelease_00-latest_weekly.xml.gz
                  - name: gcs-prefix
                    value: {{ include "argo.timestamp" . | quote }}
