##
## Copy of the base cron-workflow.yaml, substituting in altJade connection info.
## This is a temporary flow to dual write clinvar data to a separate dataset in "real" prod
## to facilitate the overall migration to that environment.
## Once we have vetted that dataset and all stakeholders are ok to switch, we should remove this
## flow and switch the primary Jade values to point at the new dataset.
##
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dual-writer-clinvar-ingest
spec:
  suspend: {{ not .Values.cron.enable }}
  schedule: {{ .Values.cron.schedule | quote }}
  timezone: {{ .Values.cron.timezone | quote }}
  concurrencyPolicy: Forbid
  workflowSpec:
    entrypoint: main
    arguments:
      parameters:
        - name: jade-dataset-id
          value: {{ .Values.altJade.datasetId }}
        - name: jade-dataset-name
          value: {{ .Values.altJade.datasetName }}
        - name: jade-data-project
          value: {{ .Values.altJade.dataProject }}
        - name: jade-url
          value: {{ .Values.altJade.url }}
        - name: jade-profile-id
          value: {{ .Values.altJade.profileId }}
        - name: channel-id
          value: {{ .Values.notification.altChannelId }}

    serviceAccountName: {{ .Values.serviceAccount.k8sName }}
    podGC:
      strategy: OnWorkflowSuccess
    onExit: {{ if .Values.notification.onlyOnFailure }}send-slack-notification-if-failed{{ else }}send-slack-notification{{ end }}
    templates:
      - name: main
        steps:
          - - name: run-main-template
              templateRef:
                name: ingest-clinvar-release-e2e
                template: main
              arguments:
                parameters:
                  - name: archive-path
                    value: weekly_release/ClinVarVariationRelease_00-latest_weekly.xml.gz
                  - name: gcs-prefix
                    value: {{ include "argo.timestamp" . | quote }}
                  - name: should-export-diff
                    value: 'false'

      ##
      ## Send a Slack notifcation if the workflow has failed.
      ##
      - name: send-slack-notification-if-failed
        steps:
          - - name: send-notification
              template: send-slack-notification
              when: '{{ "{{workflow.status}} != Succeeded" }}'

      ##
      ## Send a Slack notification describing the final status of the workflow.
      ##
      - name: send-slack-notification
        container:
          image: curlimages/curl:7.70.0
          env:
            - name: CHANNEL_ID
              value: {{ .Values.notification.altChannelId }}
            - name: WORKFLOW_ID
              value: '{{ "{{workflow.name}}" }}'
            - name: WORKFLOW_STATE
              value: '{{ "{{workflow.status}}" }}'
            - name: WORKFLOW_ENV
              value: {{ .Values.jade.environment }}
            - name: OAUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notification.oauthToken.secretName }}
                  key: {{ .Values.notification.oauthToken.secretKey }}
          command: [curl]
          args:
          - -XPOST
          - -H
          - 'Content-type: application/json'
          - -H
          - 'Authorization: Bearer $(OAUTH_TOKEN)'
          - -d
          - '{"text": "(dual writer) Workflow $(WORKFLOW_ID) in env *$(WORKFLOW_ENV)* entered state: *$(WORKFLOW_STATE)*", "channel": "$(CHANNEL_ID)"}'
          - "https://slack.com/api/chat.postMessage"
