apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: extract-clinvar-xml
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: xml-pvc-name
          - name: xml-path
      dag:
        tasks:
          - name: generate-extraction-volume
            templateRef:
              name: generate-pvc
              template: main
            arguments:
              parameters:
                - name: name-prefix
                  value: extracted-json
                - name: size
                  value: 10Gi
                - name: storage-class
                  value: standard
          - name: extract-xml
            dependencies: [generate-extraction-volume]
            templateRef:
              name: extract-xml-to-json
              template: main
            arguments:
              parameters:
                - name: input-pvc-name
                  value: '{{ "{{inputs.parameters.xml-pvc-name}}" }}'
                - name: input-xml-path
                  value: '{{ "{{inputs.parameters.xml-path}}" }}'
                - name: output-pvc-name
                  value: '{{ "{{tasks.generate-extraction-volume.outputs.parameters.pvc-name}}" }}'
      outputs:
        parameters:
          - name: pvc-name
            valueFrom:
              parameter: '{{ "{{tasks.generate-extraction-volume.outputs.parameters.pvc-name}}" }}'
