apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: extract-xml-to-json
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: input-pvc-name
          - name: input-xml-path
          - name: output-pvc-name
      volumes:
        - name: in
          persistentVolumeClaim:
            claimName: '{{ "{{inputs.parameters.input-pvc-name}}" }}'
        - name: out
          persistentVolumeClaim:
            claimName: '{{ "{{inputs.parameters.output-pvc-name}}" }}'
            readOnly: true
      container:
        image: us.gcr.io/broad-dsp-gcr-public/monster-xml-to-json-list:3.0.0
        command: []
        args:
          - --input=/in/{{ "{{inputs.parameters.input-xml-path}}" }}
          - --output=/out
          - --objects-per-part=1024
          - --gunzip-input
        volumeMounts:
          - name: in
            mountPath: /in
          - name: out
            mountPath: /out
        env:
          - name: JAVA_OPTS
            value: '-Xmx2g -Xms2g'
        resources:
          requests:
            memory: 2560Mi
            cpu: 1500m
          limits:
            memory: 2560Mi
            cpu: 1500m
