apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: extract-clinvar-release-date
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: pvc-name
          - name: file-path
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: '{{ "{{inputs.parameters.pvc-name}}" }}'
            readOnly: true
      script:
        image: python:3-slim
        command: [python]
        source: |
          import json
          with open('/state/{{ "{{inputs.parameters.file-path}}" }}') as f:
            json_data = json.load(f)
          print(json_data["ClinVarVariationRelease"]["@ReleaseDate"])
        volumeMounts:
          - name: state
            mountPath: /state
            readOnly: true
