apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ingest-clinvar-archive
spec:
  entrypoint: main
  serviceAccountName: {{ .Values.serviceAccount.k8sName }}
  templates:
    ##
    ## Entrypoint for end-to-end ETL of a ClinVar archive.
    ##
    ## Orchestrates calls to sub-workflows that know how to
    ## extract, transform, load, and publish the data.
    ##
    - name: main
      inputs:
        parameters:
          - name: archive-path
          {{- $archivePath := "{{inputs.parameters.archive-path}}" }}
          - name: gcs-prefix
          {{- $gcsPrefix := "{{inputs.parameters.gcs-prefix}}" }}
      dag:
        tasks:
          - name: ingest-archive
            templateRef:
              name: ingest-xml-archive
              template: main
            arguments:
              parameters:
                - name: archive-path
                  value: {{ $archivePath | quote }}
                - name: gcs-prefix
                  value: {{ $gcsPrefix | quote }}
            {{- $releaseDate := "{{tasks.ingest-archive.outputs.parameters.release-date}}" }}

          - name: process-archive
            dependencies: [ingest-archive]
            templateRef:
              name: process-xml-archive
              template: main
            arguments:
              parameters:
                - name: release-date
                  value: {{ $releaseDate | quote }}
                - name: gcs-prefix
                  value: {{ $gcsPrefix | quote }}
