apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ingest-clinvar-release-e2e
spec:
  entrypoint: main
  serviceAccountName: {{ .Values.serviceAccount.k8sName }}
  templates:
    ##
    ## Entrypoint for end-to-end ETL of a ClinVar archive.
    ##
    ## Orchestrates calls to sub-workflows that know how to
    ## extract, transform, load, and publish the data.
    ##
    - name: main
      inputs:
        parameters:
          - name: archive-path
          {{- $archivePath := "{{inputs.parameters.archive-path}}" }}
          - name: gcs-prefix
          {{- $gcsPrefix := "{{inputs.parameters.gcs-prefix}}" }}
      dag:
        tasks:
          - name: process-archive
            templateRef:
              name: process-and-reingest-release
              template: main
            arguments:
              parameters:
                - name: release-date
                  value: "IGNOREME"
                - name: gcs-prefix
                  value: {{ $gcsPrefix | quote }}
            {{- $datasetName := "{{tasks.process-archive.outputs.parameters.dataset-name}}" }}
          {{- $shouldExportDiff := "{{ .Values.steps.exportDiff.enabled }}" }}

          - name: export-diff
            when: {{ printf "%s == true" $shouldExportDiff | quote }}
            dependencies: [process-archive]
            templateRef:
              name: export-diff
              template: main
            arguments:
              parameters:
                - name: release-date
                  value: "IGNOREME"
                - name: dataset-name
                  value: {{ $datasetName | quote }}
                - name: gcs-prefix
                  value: {{ $gcsPrefix | quote }}
