apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ingest-clinvar-archive
spec:
  entrypoint: main
  serviceAccountName: {{ .Values.serviceAccount.k8sName }}
  templates:
    ##
    ## Entrypoint for end-to-end ETL of a ClinVar archive.
    ##
    ## Orchestrates calls to sub-workflows that know how to
    ## extract, transform, load, and publish the data.
    ##
    - name: main
      inputs:
        parameters:
          - name: archive-path
          {{- $archivePath := "{{inputs.parameters.archive-path}}" }}
          - name: gcs-prefix
          {{- $gcsPrefix := "{{inputs.parameters.gcs-prefix}}" }}
          - name: notify-clingen
          {{- $notifyClingen := "{{inputs.parameters.notify-clingen}}" }}
      dag:
        tasks:
          # Transfer and process the archive, staging outputs in GCS.
          - name: process-archive
            templateRef:
              name: process-clinvar-archive
              template: main
            arguments:
              parameters:
                - name: archive-path
                  value: '{{ $archivePath }}'
                - name: gcs-prefix
                  value: '{{ $gcsPrefix }}'
            {{- $releaseDate := "{{tasks.process-archive.outputs.parameters.release-date}}" }}

          # Ingest the raw archive into the Repository, for provenance.
          - name: ingest-raw-archive
            dependencies: [process-archive]
            templateRef:
              name: ingest-raw-archive
              template: main
            arguments:
              parameters:
                - name: gcs-prefix
                  value: '{{ $gcsPrefix }}'
                - name: release-date
                  value: '{{ $releaseDate }}'

          # Ingest the processed archive into the Repository.
          - name: ingest-processed-archive
            dependencies: [process-archive]
            templateRef:
              name: ingest-processed-archive
              template: main
            arguments:
              parameters:
                - name: gcs-prefix
                  value: '{{ $gcsPrefix }}'
                - name: release-date
                  value: '{{ $releaseDate }}'
                - name: publish-kafka
                  value: '{{ $notifyClingen }}'
            {{- $ingestSummary := "{{tasks.ingest-processed-archive.outputs.parameters.summary}}" }}
