apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: process-and-reingest-release
spec:
  entrypoint: main
  serviceAccountName: {{ .Values.serviceAccount.k8sName }}
  templates:
    {{- $pipelineVersion := default "latest" .Values.version }}
    {{- $versionIsPinned := ne $pipelineVersion "latest" }}

    ##
    ## Entrypoint for processing a ClinVar archive.
    ##
    ## Converts the archive to JSON and processes it with Dataflow,
    ## then pushes the result into the TDR.
    ##
    - name: main
      inputs:
        parameters:
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
          - name: gcs-prefix
          {{- $gcsPrefix := "{{inputs.parameters.gcs-prefix}}" }}

      outputs:
        parameters:
          - name: dataset-name
            value: "IGNOREME"
