apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: publish-clinvar-archive
spec:
  entrypoint: main
  serviceAccountName: {{ .Values.serviceAccount.k8sName }}
  templates:
    ##
    ## Entrypoint for publishing ingested ClinVar data to downstream consumers.
    ##
    ## NOT idempotent (How can/should we deal with that?)
    ##
    - name: main
      inputs:
        parameters:
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
          - name: ingest-summary
          {{- $ingestSummary := "{{inputs.parameters.ingest-summary}}" }}
      dag:
        tasks:
          - name: notify-clingen-kafka
            template: notify-clingen-kafka
            arguments:
              parameters:
                - name: release-date
                  value: '{{ $releaseDate }}'
                - name: ingest-summary
                  value: '{{ $ingestSummary }}'

    ##
    ## Send a Kafka message to ClinGen, pointing them at newly-ingested data.
    ##
    - name: notify-clingen-kafka
      inputs:
        parameters:
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
          - name: ingest-summary
          {{- $ingestSummary := "{{inputs.parameters.ingest-summary}}" }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/clingen-notifier:1.0.0
        env:
          - name: RELEASE_DATE
            value: '{{ $releaseDate }}'
          - name: GCS_BUCKET
            value: '{{ .Values.gcs.resultBucketName }}'
          - name: INGEST_SUMMARY
            value: '{{ $ingestSummary }}'
          - name: KAFKA_TOPIC
            value: '{{ .Values.kafka.topic }}'
        envFrom:
          - secretRef:
              name: '{{ .Values.kafka.secretName }}'
        command: [python]
        source: |
        {{- include "argo.render-lines" (.Files.Lines "scripts/notify-clingen-kafka.py") | indent 10 }}
