apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: rsync-to-gcs
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: pvc-name
          - name: local-prefix
          - name: gcs-bucket
          - name: gcs-prefix
          - name: max-concurrent-uploads
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: '{{ "{{inputs.parameters.pvc-name}}" }}'
            readOnly: true
      container:
        image: google/cloud-sdk:slim
        command: [gsutil]
        args:
          - -m
          - rsync
          - -r
          - /state/{{ "{{inputs.parameters.local-prefix}}" }}
          - gs://{{ "{{inputs.parameters.gcs-bucket}}" }}/{{ "{{inputs.parameters.gcs-prefix}}" }}
        volumeMounts:
          - name: state
            mountPath: /state
            readOnly: true
      podSpecPatch: |
        containers:
          - name: main
            resources:
              requests:
                memory: {{ "{{inputs.parameters.max-concurrent-uploads}}Gi" }}
                cpu: {{ "{{inputs.parameters.max-concurrent-uploads}}000m" }}
              limits:
                memory: {{ "{{inputs.parameters.max-concurrent-uploads}}Gi" }}
                cpu: {{ "{{inputs.parameters.max-concurrent-uploads}}000m" }}
      retryStrategy:
        limit: 32
