apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: snapshot-dataset
spec:
  entrypoint: main
  serviceAccountName: {{ .Values.serviceAccount.k8sName }}
  templates:
    ##
    ## Entrypoint for freezing the current state of the ClinVar dataset as a snapshot.
    ##
    - name: main
      inputs:
        parameters:
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
      dag:
        tasks:
          - name: get-snapshot-info
            template: get-snapshot-info
            arguments:
              parameters:
                - name: release-date
                  value: {{ $releaseDate | quote }}
          {{- $snapshotName := "{{tasks.get-snapshot-info.outputs.parameters.name}}" }}
          {{- $snapshotDescription := "{{tasks.get-snapshot-info.outputs.parameters.description}}" }}

          - name: submit-job
            dependencies: [get-snapshot-info]
            template: submit-full-view-snapshot
            arguments:
              parameters:
                - name: snapshot-name
                  value: {{ $snapshotName | quote }}
                - name: snapshot-description
                  value: {{ $snapshotDescription | quote }}
          {{ $jobId := "{{tasks.submit-job.outputs.result}}" }}

          - name: poll-job
            dependencies: [submit-job]
            template: poll-ingest-job
            arguments:
              parameters:
                - name: job-id
                  value: {{ $jobId | quote }}
                {{- with .Values.jade }}
                - name: api-url
                  value: {{ .url }}
                - name: timeout
                  value: {{ .pollTimeout | quote }}
                - name: sa-secret
                  value: {{ .accessKey.secretName }}
                - name: sa-secret-key
                  value: {{ .accessKey.secretKey }}
                {{- end }}

    ##
    ## Transform a release-date into a TDR snapshot name.
    ##
    - name: get-snapshot-info
      inputs:
        parameters:
          - name: release-date
          {{- $releaseDate := "{{inputs.parameters.release-date}}" }}
      script:
        image: python:3-slim
        command: [python]
        source: |
          release_date = '{{ $releaseDate }}'
          snapshot_name = f"clinvar_{release_date.replace('-', '_')}"
          snapshot_description = f"Mirror of NCBI's ClinVar archive as of {release_date}"

          with open('/name.txt', 'w') as namefile:
            namefile.write(snapshot_name)
          with open('/description.txt', 'w') as descriptionfile:
            descriptionfile.write(snapshot_description)
      outputs:
        parameters:
          - name: name
            valueFrom:
              path: /name.txt
          - name: description
            valueFrom:
              path: /description.txt

    ##
    ## Submit a job to the TDR which will create a snapshot of all live data in a dataset.
    ##
    - name: submit-full-view-snapshot
      inputs:
        parameters:
          - name: snapshot-name
          {{- $snapshotName := "{{inputs.parameters.snapshot-name}}" }}
          - name: snapshot-description
          {{- $snapshotDescription := "{{inputs.parameters.snapshot-description}}" }}
      volumes:
        {{- with .Values.jade }}
        - name: sa-secret-volume
          secret:
            secretName: {{ .accessKey.secretName }}
      script:
        image: us.gcr.io/broad-dsp-gcr-public/monster-auth-req-py:1.0.1
        volumeMounts:
          - name: sa-secret-volume
            mountPath: /secret
        env:
          - name: API_URL
            value: {{ .url }}
          - name: DATASET_NAME
            value: {{ .datasetName }}
          - name: PROFILE_ID
            value: {{ .profileId }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ printf "/secret/%s" .accessKey.secretKey }}
        {{- end }}
          - name: SNAPSHOT_NAME
            value: {{ $snapshotName | quote }}
          - name: SNAPSHOT_DESCRIPTION
            value: {{ $snapshotDescription | quote }}
        command: [python]
        source: |
        {{- include "argo.render-lines" (.Files.Lines "scripts/request-full-view-snapshot.py") | indent 10 }}

    ## Inject template used to poll TDR jobs.
    {{- include "argo.poll-ingest-job" . | indent 4 }}
