volumes:
  storageClass: standard
  downloadSize: 1Gi
  extractSize: 10Gi
cron:
  enable: true
  # Every Sunday at 3:30am
  schedule: '30 3 * * Sun'
  timezone: 'America/New_York'
dataflow:
  region: us-central1
  workerMachineType: n1-standard-4
  autoscaling:
    minWorkers: 4
    maxWorkers: 8
  useFlexRS: false
bigquery:
  jadeData:
    dataset: datarepo_broad_dsp_clinvar
maxParallelism: 16
