name: Master Validation and Release
on:
  push:
    branches:
      - master
jobs:
  master-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch tag history
        run: git fetch --tags
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: graalvm@20.0.0
#      - name: Check formatting
#        run: sbt scalafmtCheckAll
      - name: Compile
        run: sbt Compile/compile # Test/compile
#      - name: Test
#        run: sbt "set ThisBuild/coverageEnabled := true" test coverageAggregate
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.Base64ServiceAccountKey }}'
      - uses: google-github-actions/setup-gcloud@v1
        env:
          CLOUDSDK_PYTHON: python3
        with:
          version: '286.0.0'
          project_id: broad-dsp-monster-dev
#          service_account_email: jenkins-gcr-pusher@broad-dsp-monster-dev.iam.gserviceaccount.com
#          service_account_key: ${{ secrets.Base64ServiceAccountKey }}
          export_default_credentials: true
      - name: Setup GCR auth
        run: gcloud auth configure-docker --quiet
      - name: Publish
        run: sbt publish
