name: PR Validation
on:
  pull_request:
    branches:
      - master
jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: broadinstitute/setup-chart-releaser@v0
        with:
          version: 'latest'
      - run: which cr
